FROM node:20-alpine3.20

WORKDIR /tmp

COPY index.min.js html/en/index.html package.json ./

# 主要起声明和辅助作用,而非强制性的网络配置; 它主要是一个 元数据 (Metadata), 告诉阅读 Dockerfile 的人或维护者: "这个应用程序默认监听 TCP 协议的 7860 端口".
# 它不会自动把容器的 7860 端口映射到宿主机, 当你使用命令 docker run -P (大写的 P) 启动容器时, Docker 会自动扫描镜像中所有 EXPOSE 的端口, 并将它们随机映射到宿主机的高位端口 (Ephemeral Ports) 上
# EXPOSE 7860

RUN apk update && apk add --no-cache bash openssl curl &&\
    chmod +x index.min.js &&\
    npm install

CMD ["node", "index.min.js"]
